"""
Builds the HTML digest email and sends it over plain SMTP.
Gmail works fine with an app password. No paid email service needed.
"""

import html
import smtplib
import datetime as dt
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart

import config

CSS = """
body { font-family: -apple-system, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
       color: #1a1a1a; background: #f5f5f4; margin: 0; padding: 24px; }
.wrap { max-width: 680px; margin: 0 auto; }
h1 { font-size: 20px; margin: 0 0 4px; }
.sub { color: #6b6b6b; font-size: 13px; margin-bottom: 24px; }
.card { background: #fff; border: 1px solid #e4e4e2; border-radius: 8px;
        padding: 18px 20px; margin-bottom: 14px; }
.card h2 { font-size: 17px; margin: 0 0 2px; }
.meta { color: #6b6b6b; font-size: 12px; margin-bottom: 12px; }
.score { display: inline-block; font-size: 12px; font-weight: 600; padding: 3px 9px;
         border-radius: 20px; color: #fff; vertical-align: middle; margin-left: 8px; }
.hot { background: #b91c1c; } .warm { background: #c2670a; } .cool { background: #3f6212; }
ul { margin: 0 0 12px; padding-left: 18px; }
li { font-size: 14px; line-height: 1.55; margin-bottom: 4px; }
.roles { border-top: 1px solid #eeeeec; padding-top: 10px; margin-top: 10px; }
.roles a { color: #1d4ed8; text-decoration: none; font-size: 13px; }
.tag { display: inline-block; background: #f0efec; border-radius: 4px; padding: 2px 7px;
       font-size: 11px; color: #4b4b4b; margin: 0 4px 4px 0; }
.foot { color: #8a8a8a; font-size: 11px; text-align: center; margin-top: 24px; }
"""


def _band(score):
    if score >= 80:
        return "hot", "Hot"
    if score >= 50:
        return "warm", "Warm"
    return "cool", "Watch"


def build_html(accounts, run_date=None):
    run_date = run_date or dt.date.today().strftime("%d %b %Y")
    parts = [
        f"<html><head><meta charset='utf-8'><style>{CSS}</style></head><body><div class='wrap'>",
        f"<h1>Account signals</h1>",
        f"<div class='sub'>{run_date} &middot; {len(accounts)} account(s) worth a look</div>",
    ]

    if not accounts:
        parts.append("<div class='card'>No accounts crossed the score threshold today.</div>")

    for acc in accounts:
        cls, label = _band(acc["score"])
        d = acc["detail"]
        parts.append("<div class='card'>")
        parts.append(
            f"<h2>{html.escape(acc['company'])}"
            f"<span class='score {cls}'>{label} {acc['score']}</span></h2>"
        )
        parts.append(
            f"<div class='meta'>Est. size {html.escape(str(d.get('estimated_size', 'unknown')))}"
            f" &middot; {d.get('total_open_roles', 0)} open roles</div>"
        )

        parts.append("<ul>")
        for reason in acc["reasons"]:
            parts.append(f"<li>{html.escape(reason)}</li>")
        parts.append("</ul>")

        tags = (d.get("observability_stack", []) + d.get("cloud", []))[:8]
        if tags:
            parts.append("".join(f"<span class='tag'>{html.escape(t)}</span>" for t in tags))

        roles = d.get("reliability_roles", [])
        if roles:
            parts.append("<div class='roles'>")
            for r in roles:
                loc = f" &middot; {html.escape(r['location'])}" if r.get("location") else ""
                if r.get("url"):
                    parts.append(f"<div><a href='{html.escape(r['url'])}'>{html.escape(r['title'])}</a>{loc}</div>")
                else:
                    parts.append(f"<div>{html.escape(r['title'])}{loc}</div>")
            parts.append("</div>")

        if acc.get("funding_url"):
            parts.append(
                f"<div class='roles'><a href='{html.escape(acc['funding_url'])}'>Funding source</a></div>"
            )
        if d.get("flag"):
            parts.append(f"<div class='meta' style='margin-top:8px'>{html.escape(d['flag'])}</div>")
        parts.append("</div>")

    parts.append("<div class='foot'>Generated by your account signal bot</div>")
    parts.append("</div></body></html>")
    return "".join(parts)


def build_text(accounts):
    lines = [f"Account signals, {dt.date.today():%d %b %Y}", ""]
    for acc in accounts:
        lines.append(f"{acc['company']}  [score {acc['score']}]")
        for reason in acc["reasons"]:
            lines.append(f"  - {reason}")
        lines.append("")
    return "\n".join(lines) or "No accounts today."


def send(accounts, to=None, dry_run=False, out_path="digest_preview.html"):
    html_body = build_html(accounts)

    if dry_run or not config.SMTP_USER:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(html_body)
        print(f"Dry run. Preview written to {out_path}")
        return False

    msg = MIMEMultipart("alternative")
    msg["Subject"] = config.EMAIL_SUBJECT.format(date=dt.date.today().strftime("%d %b"))
    msg["From"] = config.SMTP_USER
    msg["To"] = to or config.EMAIL_TO
    msg.attach(MIMEText(build_text(accounts), "plain"))
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP(config.SMTP_HOST, config.SMTP_PORT) as server:
        server.starttls()
        server.login(config.SMTP_USER, config.SMTP_PASS)
        server.send_message(msg)

    print(f"Digest sent to {to or config.EMAIL_TO}")
    return True
